### PR TITLE
Replaced minimatch with micromatch

### PR DESCRIPTION
**Pull request by JacobMillward**
minimatch only allows matching against a single pattern, whereas multimatch can match against an array of patterns, making more complex exclusions/inclusions possible.

### CODE REVIEW

**Comment by whymarrh** [comment]
Hey, thanks for the PR! Would you mind updating the description to briefly include why you think this is needed? (I haven't looked at minimatch or multimatch in a while.) As well it looks like a few of the tests are failing, would you mind taking a look at those?

**Comment by JacobMillward** [comment]
I've updated the description!
I'll take a look at the tests and see what I can do.

**Comment by whymarrh** [comment]
> I've updated the description!

Looks good, thanks!

> I'll take a look at the tests and see what I can do.

Ask away if you have any questions as well! Feel free to update Jest or anything if you need to.

**Comment by whymarrh** [comment]
Hey, any luck with this?

**Comment by JacobMillward** [comment]
I sent you an email the other night, I've no idea why the tests are failing! I just can't figure it out!

**Comment by whymarrh** [comment]
What issue(s) are you running into? From a quick look at the build on Travis CI, you will need to add a new Jest mock for the new package (Jest has automock enabled).

**Comment by whymarrh** [comment]
Hey, did you have another go at this afterwards?

I should have some time this weekend to merge this if we can get the checks passing.

**Comment by JacobMillward** [comment]
I've been trying to get these tests to pass for ages. I've even replaced multimatch with micromatch (seems more featureful as well) in order to see whats going on and I've honestly no idea. I think I don't have a good enough handle on jest, as I've not used it before.

**Comment by whymarrh** [comment]
It looks like the tests are passing on Travis with your latest changes! There are a few code style things jscs pointed out but if you fix those you should be all set.

**Comment by JacobMillward** [comment]
Ok, that's very odd. The tests fail horribly on both my desktop, and my laptop. Even running jscs locally returns different styling errors. What is going on here?
```
PS C:\Users\Admin\Dev\metalsmith-html-minifier> npm run test

> metalsmith-html-minifier@2.2.0 test C:\Users\Admin\Dev\metalsmith-html-minifier
> jest && jscs lib __tests__ __mocks__

 FAIL  __tests__\minifier.js
  ● metalsmith-html-minifier › should call minify with each HTML files' contents

    expect(received).toBe(expected)

    Expected value to be (using ===):
      2
    Received:
      0

      at Object.<anonymous> (__tests__\minifier.js:42:36)
          at <anonymous>

  ● metalsmith-html-minifier › should call minify with default options when no options given

    expect(received).toBe(expected)

    Expected value to be (using ===):
      1
    Received:
      0

      at Object.<anonymous> (__tests__\minifier.js:62:36)
          at <anonymous>

  ● metalsmith-html-minifier › should call minify with options as first argument

    expect(jest.fn()).toBeCalledWith(expected)

    Expected mock function to have been called with:
      ["a", {"collapseBooleanAttributes": true, "collapseWhitespace": true, "foo": "bar", "pattern": "**/*.html", "remov
eAttributeQuotes": true, "removeComments": true, "removeEmptyAttributes": true, "removeRedundantAttributes": true}]
    But it was not called.

      at Object.<anonymous> (__tests__\minifier.js:88:18)

  metalsmith-html-minifier
    √ should be a function (342ms)
    √ should return a function (35ms)
    × should call minify with each HTML files' contents (23ms)
    × should call minify with default options when no options given (31ms)
    × should call minify with options as first argument (16ms)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 2 passed, 5 total
Snapshots:   0 total
Time:        1.358s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! metalsmith-html-minifier@2.2.0 test: `jest && jscs lib __tests__ __mocks__`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the metalsmith-html-minifier@2.2.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2017-09-30T16_50_47_302Z-debug.log
```

**Comment by whymarrh** [comment]
I'll check out this PR locally and see what's up

**Comment by whymarrh** [comment]
The tests don't pass for me locally either 😕 so I'm not sure why they're passing on Travis. That said, here's what I looked at:

1. While the plugin correctly passes its errors along to its callback, the tests do not handle them. So... that's a thing (sorry!). Adding `console.error(e)` to the catch block will reveal the issue with the tests:

       console.error lib/index.js:40
         TypeError: use: expect `app` be an object or function
             at base (/Projects/metalsmith-html-minifier/node_modules/use/index.js:14:11)
             at Object.Compiler (/Projects/metalsmith-html-minifier/node_modules/snapdragon/lib/compiler.js:28:3)
             at new Snapdragon (/Projects/metalsmith-html-minifier/node_modules/snapdragon/index.js:25:19)
             at Object.<anonymous>.utils.instantiate (/Projects/metalsmith-html-minifier/node_modules/micromatch/lib/utils.js:43:18)
             at parse (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:738:28)
             at memoize (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:866:13)
             at Function.Object.<anonymous>.micromatch.parse (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:752:10)
             at create (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:688:44)
             at /Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:697:16
             at memoize (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:866:13)
             at Function.Object.<anonymous>.micromatch.create (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:686:10)
             at makeRe (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:581:29)
             at memoize (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:866:13)
             at Function.Object.<anonymous>.micromatch.makeRe (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:598:10)
             at matcher (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:485:23)
             at memoize (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:866:13)
             at Function.Object.<anonymous>.micromatch.isMatch (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:168:17)
             at Function.Object.<anonymous>.micromatch.all (/Projects/metalsmith-html-minifier/node_modules/micromatch/index.js:316:21)
             at /Projects/metalsmith-html-minifier/lib/index.js:31:20
             at Array.forEach (native)
             at plugin (/Projects/metalsmith-html-minifier/lib/index.js:30:4)
             at Object.<anonymous> (/Projects/metalsmith-html-minifier/__tests__/minifier.js:35:3)
        ... truncated for brevity ...

    What does this mean? I don't know.

2. Checking out 7554dd6 (your first commit in this PR, the one with multimatch) seems to work after updating the Jest mock file:

        15:39:51 metalsmith-html-minifier ((7554dd6...) %) $ mv __mocks__/{mini,multi}match.js
        15:40:09 metalsmith-html-minifier ((7554dd6...) *%) $ vim __mocks__/multimatch.js 
        15:40:19 metalsmith-html-minifier ((7554dd6...) *%) $ npm t
        
        > metalsmith-html-minifier@2.2.0 test /Projects/metalsmith-html-minifier
        > jest && jscs lib __tests__ __mocks__
        
         PASS  __tests__/minifier.js
          metalsmith-html-minifier
            ✓ should be a function (272ms)
            ✓ should return a function (6ms)
            ✓ should call minify with each HTML files' contents (11ms)
            ✓ should call minify with default options when no options given (6ms)
            ✓ should call minify with options as first argument (4ms)
        
        Test Suites: 1 passed, 1 total
        Tests:       5 passed, 5 total
        Snapshots:   0 total
        Time:        2.211s
        Ran all test suites.
        requireSpaceAfterKeywords: One space required after "if" keyword at lib/index.js :
            29 |   Object.keys(files)
            30 |   .forEach(function (file) {
            31 |    if(multimatch(file, options.pattern).length){
        --------------^
            32 |     var data = files[file];
            33 |     var contents = data.contents.toString();
        
        
        1 code style error found.
        npm ERR! Test failed.  See above for more details.


If you're interested in digging into micromatch doesn't work 👍🏽 but I don't have a desire to 🙂. Where your previous proposal of multimatch seems to work fine, if you want to revert this PR back to that and fix the few jscs errors I'll happily merge that too.

(I have literally zero clues about why the tests pass on Travis. For the record, I was testing with node v6.11.3 and 3.10.10.)

**Comment by JacobMillward** [comment]
7554dd6 doesn't pass for me either. I'm on Node 8.6.0, but I can't imagine why, or if, that would change anything.

The travis build for those changes didn't work either.  This is the travis build for that (the merge).
https://travis-ci.org/whymarrh/metalsmith-html-minifier/builds/276893181

**Comment by whymarrh** [comment]
7554dd6 requires updating to rename the jest mock IIRC

**Comment by JacobMillward** [comment]
Ok, looks to be passing now.

**Comment by whymarrh** [comment]
Cool, thanks for sticking with this 🎉

**Comment by whymarrh** [comment]
I'll be sure to get a release out tomorrow. Thanks again!

**Comment by whymarrh** [comment]
This has been released as part of v2.4.3!

**Pull request merged**
